### ISSUE TITLE
pressions non filtrées selon le type de masse d'eau sélectionné

### ISSUE THREAD

**Issue by Arkhee** [Arkhee/sdage-consultations2018#1]
"à l’usage, il serait bien que les pressions soient filtrées sur les catégories. Cela serait un +"
Le fait de ne pas établir ce lien avait été discuté en réunion, du coup la conception de l'outil s'est faite sans et pour le rajouter cela nécessite des modifications à plusieurs niveaux de l'application, impliquant une phase de retest, après un temps d'implémentation.
Vu le nombre de pressions je suggère de voir s'il y a des retours utilisateur en ce sens.

**Comment by fabiennebarratier** [comment]
ok, nous pouvons avoir quelques confusions sur des pressions qui ne sont pas concernées par des masses d'eau. 
nous verrons à l'usage.
