### ISSUE TITLE
pas toujours de bouton de suppression de PJ visible lorsqu'un avis est en édition

### ISSUE THREAD

**Issue by Arkhee** [Arkhee/sdage-consultations2018#4]
Le problème se produisait lorsque l'avis en était à sa première édition, c'est corrigé (ajout dynamique de ce bouton de suppression même lors du premier affichage
a tester

**Comment by fabiennebarratier** [comment]
la corbeille est bien présente, mais elle ne permet pas de supprimer la PJ.

**Comment by Arkhee** [comment]
il y avait quelques inconsistances, maintenant la corbeille disparaît bien systématiquement lorsque la PJ est supprimée, après validation de la popup de confirmation de suppression
J'ai aussi ajouté des popup qui devraient apparaître en cas d'erreur de sauvegarde d'une pièce jointe (extension interdite ou problème sur le serveur)

**Comment by fabiennebarratier** [comment]
Après un test, la corbeille ne supprime pas la PJ.
une fois la sauvegarde de l'avis, la PJ est toujours visible

**Comment by Arkhee** [comment]
j'ai refait une série de test et je n'arrive pas à reproduire ce problème, peux-tu essayer de rafraichir le navigateur avec "CTRL+F5" afin de bien nettoyer le cache du navigateur (certains bouts de programmation, ceux en javascript, peuvent parfois rester ancrés dans le cache).
D'autre par j'aurais besoin de détails sur la manip de suppression: 
* depuis la recherche ou depuis l'espace perso ?
* en premier ajout de PJ ou après un ajout ?
* après rafraichissement de la page ou directement après ?

**Comment by fabiennebarratier** [comment]
je fais le test à partir d'une recherche ME
la corbeille fonctionne si la PJ se trouve à côté de la corbeille
mes tests n'enregistraientt pas la PJ à côté de la corbeille, la PJ restait dans la cellule de chargement.
c'est en faisant un F5 (rafraichissement) que la PJ a basculé de la cellule de chargement à son emplacement (à côté de la corbeille)
voir ce que tu peux faire pour éviter ce dysfonctionnement

**Comment by Arkhee** [comment]
ok je vois : mais en pratique la corbeille supprime effectivement la pièce qui vient tout juste d'être soumise, on peut le vérifier en ouvrant la recherche dans un autre onglet puis en accédant à l'avis : il y a la PJ, et quand on la supprime depuis le premier onglet, la PJ disparaît bien dans le second onglet après rafraichissement.
En revanche comme c'est la mise en ligne initiale, le nom et le lien de la PJ n'est pas ré-affiché automatiquement après soumission dans la popup, je pensais que ça convenait car on n'en avait par reparlé. Je vais faire en sorte que le nom s'affiche après le submit, ce sera plus clair.

**Comment by Arkhee** [comment]
point corrigé, à tester

**Comment by fabiennebarratier** [comment]
le comportement de l'application n'est pas idéal pour avoir re-testé, mais si je rafraîchie la page (F5) la corbeille permet de supprimer la PJ comme demandée.

**Comment by Arkhee** [comment]
réglé

**Comment by fabiennebarratier** [comment]
d'après mon test : ajout d'une PJ/sauvegarde de l'avis/fermeture de l'avis puis ouverture avis/suppression PJ / validation avis/ouverture avis : la PJ est encore présente dans l'avis alors qu'il est validé. avis n°47

**Comment by Arkhee** [comment]
ok je pense que c'est parce que le champ de formulaire contenant la PJ n'était pas nettoyé entretemps, en pratique ça a peu de chance de se produire car logiquement les utilisateurs devraient soit décider de valider immédiatement (sans supprimer leur pj) soit revenir un peu plus tard et là le champ sera nettoyé

J'ai mis en place un nettoyage du champ de formulaire de la PJ pour être sûr que la pièce ne soit pas renvoyée par erreur quand même, le nettoyage se produit : après la sauvegarde de l'avis, après la suppression de l'avis, après la validation de l'avis (normalement il n'est nécessaire qu'après la sauvegarde de l'avis en pratique)

**Comment by fabiennebarratier** [comment]
la suppression de la PJ fonctionne
merci
