### ISSUE TITLE
AVIS / PDF - ajouter le nom du créateur et le nom de la structure

### ISSUE THREAD

**Issue by fabiennebarratier** [Arkhee/sdage-consultations2018#5]
Ajouter le nom du créateur de l'avis et la structure sur le pdf de 'avis.

**Comment by Arkhee** [comment]
fait, et mis certaines informations en ligne pour recompacter un peu l'affichage, qui commence à s'étendre un peu trop verticalement, ok ainsi ?

**Comment by fabiennebarratier** [comment]
si on ajoute le prénom de la personne, cela me convient.

**Comment by Arkhee** [comment]
ah exact, autant pour moi je me suis laissé avoir par les premières lignes de données, où nom et prénom sont dans la même case, c'est corrigé

**Comment by fabiennebarratier** [comment]
ok cela me convient
