### ISSUE TITLE
EXPORT - Télécharger tous les avis déposés au format CSV

### ISSUE THREAD

**Issue by fabiennebarratier** [Arkhee/sdage-consultations2018#6]
il reste des pb de caractère sous excel
ex :
1.	La masse d'eau est l'unitÃ© spatiale pour identifier les mesures Ã  conduire pour atteindre des objectifs de bon Ã©tat des eaux dÃ©finis par la directive cadre sur l'eau. De quelques km Ã  quelques dizaines de km pour les cours d'eau et eaux cÃ´tiÃ¨res, de quelques dizaines d'hectares Ã  quelques dizaines de KmÂ² pour les plans d'eau et lagunes, et de plusieurs dizaines de KmÂ² pour les eaux souterraines. Cette unitÃ© est dÃ©sormais couramment utilisÃ©e par les acteurs. 
ïƒ°	Les avis demandÃ©s doivent reposer sur des apprÃ©ciations (1) des impacts des activitÃ©s humaines Ã  l'Ã©chelle de la taille des masses d'eau (sans considÃ©rer les impacts trÃ¨s localisÃ©s)  et (2) des pressions sur lesquelles agir pour restaurer l'Ã©tat des eaux Ã  ces Ã©chelles.
2.	Les impacts qualifient l'incidence des pressions humaines sur chaque masse d'eau. Leur Ã©valuation sert Ã  identifier les pressions qui peuvent empÃªcher d'atteindre le bon Ã©tat. L'estimation de ces  impacts a Ã©tÃ© rÃ©alisÃ©e avec des donnÃ©es de la surveillance des milieux (qualitÃ© et quantitÃ©) du bassin, des Ã©tudes locales et de donnÃ©es sur les pressions issues d'outils et mÃ©thodes nationaux ou de bassin. Elle possÃ¨de une validitÃ© statistique fondÃ©e sur des chroniques de donnÃ©es pluriannuelles et des approches modÃ©lisÃ©es adaptÃ©es Ã  l'Ã©chelle et au contexte du bassin. Elle n'a pas pour objet de rendre compte des hÃ©tÃ©rogÃ©nÃ©itÃ©s locales mais au contraire de faire ressortir les situations contrastÃ©es entre les masses d'eau. Leur expertise par les acteurs consultÃ©s demande une connaissance de l'Ã©tendue des secteurs dÃ©gradÃ©s ou menacÃ©s, des points de pollution ou obstacles majeurs â€¦ ainsi que, le cas Ã©chÃ©ant, une expertise des effets des travaux rÃ©alisÃ©s, en application des programmes de mesures des SDAGE 2010-2015 et 2016-2021. 
ïƒ°	Il est demandÃ© d'apprÃ©cier, Ã  dire d'expert, les niveaux d'impacts proposÃ©es (1-faible ;           2-moyen ; 3-fort), en les comparant Ã  la connaissance de la situation des masses d'eau par les acteurs de terrain. Il n'est pas attendu procÃ©der Ã  une vÃ©rification des donnÃ©es et des mÃ©thodes utilisÃ©es pour produire les Ã©valuations proposÃ©es.
ïƒ°	Les demandes d'ajustement des impacts devront Ãªtre fondÃ©es sur une connaissance actuelle de la dimension des problÃ¨mes rencontrÃ©s (ex : ordres de grandeur des linÃ©aires ou superficies concernÃ©es). 
3.	Les pressions Ã  l'origine du risque de non-atteinte des objectifs environnementaux subies par chaque masse d'eau sont celles dont l'effet est significatif par rapport Ã  la taille de la masse d'eau, seules (pression dont l'impact est jugÃ© fort) ou en association avec d'autres pressions (combinaison de plusieurs pressions dont l'impact individuel est moyen) pour Ãªtre Ã  l'origine d'une dÃ©gradation actuelle ou d'une menace de dÃ©gradation Ã  un horizon proche (Â« pressions importantes Â»). Le travail de co-construction du programme de mesures portera sur ces pressions.

**Comment by Arkhee** [comment]
comme indiqué précédemment, le format UTF8 n'est pas le format d'ouverture par défaut de Excel (c'est pour ça qu'on était repassé sur le latin1 pendant les réunions de préparation), pour ouvrir le fichier sous excel il faut faire en plusieurs étapes, par exemple pour excel 2016 (voire 2013) : 
- lancer excel et créer un nouveau document
- Données => A partir d'un fichier texte / csv
- Sélectionner dans "Origine du fichier" le format "UTF8"

Ou sinon avec notepad++ utiliser la fonction de conversion vers ANSI, là le double-click devrait fonctionner

![screen-excel-import-utf8](https://user-images.githubusercontent.com/3664145/41274768-e6531c24-6e1e-11e8-8c4a-63eb9ac9099a.jpg)

**Comment by fabiennebarratier** [comment]
j'ai fait  un test sous excel en important à partir de données/à partir du texte/ le fichier csv. je n'ai plus les problèmes signalés de texte, mais les sauts de ligne sont mal gérés. Ex masse d'eau FRDG104, avis 14.

**Comment by Arkhee** [comment]
l'import CSV n'augmente pas automatiquement la hauteur de la ligne, par contre quand on clique dessus on peut déployer le champ et les retours chariot me semblent conformes entre la base, l'affichage dans le PDF et le champ dans excel
![avis14-screen-db](https://user-images.githubusercontent.com/3664145/41297021-7e18f364-6e5e-11e8-8cea-eb7f026cefe0.jpg)
![avis14-screen-excel](https://user-images.githubusercontent.com/3664145/41297022-7e38958e-6e5e-11e8-9f8d-ffb15373274f.jpg)
![avis14-screen-pdf](https://user-images.githubusercontent.com/3664145/41297023-7e52c396-6e5e-11e8-8f42-61325c5c1677.jpg)

**Comment by fabiennebarratier** [comment]
j'ai fait un test sur un export des avis validés par un créateur. le fichier dysfonctionne complètement

**Comment by Arkhee** [comment]
j'ai bien reçu le fichier, par contre, à part les colonnes en plus par rapport à l'export collaborateur (mais il me semblait avoir compris qu'on les gardait pour les utilisateurs ?) je ne vois pas le problème.

quand un problème se pose idéalement, comme ce problème ne se pose pas forcémment à l'identique dans toutes les situations, il faudrait décrire plus avant le dysfonctionnement observé

**Comment by fabiennebarratier** [comment]
le test porte sur un import à partir d'Excel
données/à partir du texte
si je demandé fichier délimité/point virgule... je pense que la colonne de commentaire ne s'importe pas correctement, les informations sont réparties sur toutes les autres colonnes

**Comment by Arkhee** [comment]
c'est peut-être un problème de réglages ou de logiciel ? voici le fichier que j'obtiens à l'import dans excel, en suivant la procédure d'import de csv décrite ci-dessus. 
A noter qu'en double-cliquant sur le fichier j'obtiens un fichier correctement formatté mais avec les problèmes de caractères bien sûr.
[test_fichier_export.xlsx](https://github.com/Arkhee/sdage-consultations2018/files/2094710/test_fichier_export.xlsx)

**Comment by fabiennebarratier** [comment]
le test que j'effectue n'est pas réalisé à partir de l'application, il est réalisé si l'utilisateur enregistre le fichier dans un dossier et l'importe ensuite dans excel.
si je fais le test depuis l'application, je ne rencontre pas de problème de décalage de colonne juste des problèmes de caractère. comment pouvons nous corriger ces problèmes de caractères ?

**Comment by Arkhee** [comment]
c'est aussi le test que j'ai fait : enregistrer le fichier et ouverture dans excel, sans problème de colonne, cf. fichier xlsx ci-dessus

quand on ouvre un CSV directement dans excel les éventuels bugs peuvent dépendre de la version d'excel (ou d'openoffice) utilisée

les problèmes de caractères bizarres à la place des accents ne peuvent être "résolus" car il ne s'agit pas d'un bug : le fichier est en UTF8, avec des accents encodés en 2 caractères, et excel essaye par défaut de les ouvrir en latin1, avec des accents encodés en un seul caractère. 
c'est donc normal que excel mettre 2 caractères bizarres à la place des caractères accentués, c'est lié à l'utf8. le bug c'est que excel ne détecte pas automatiquement que le fichier est en utf8 mais ça on ne peut rien y faire.

**Comment by fabiennebarratier** [comment]
ok, on va resté comme cela.
le plus important étant le fichier que l'on importera dans l'autre application..

**Comment by Arkhee** [comment]
à priori ok maintenant ? je clos le ticket

**Comment by fabiennebarratier** [comment]
ok, j'ai refais le point sur les fichiers exportés. Tout est ok
merci
