### ISSUE TITLE
Message erreur : avis : rédaction d'une justification

### ISSUE THREAD

**Issue by fabiennebarratier** [Arkhee/sdage-consultations2018#7]
j'ai fait un copier/coller dans la case justification : voir le texte ci dessous. lorsque je sauvegarde l'avis, un message d'erreur s'affiche : erreur pour import de la pièce jointe : extension interdite. l''avis est sauvegardé malgré tout. Si je valide, j'ai le même message d'erreur, mais la validation est ok.

Etat des lieux du bassin Rhône-Méditerranée 2019
Consultation sur le niveau d’impact des pressions sur les masses d’eau
Précisions et consignes pour une consultation efficace
1.	La masse d’eau est l’unité spatiale pour identifier les mesures à conduire pour atteindre des objectifs de bon état des eaux définis par la directive cadre sur l’eau. De quelques km à quelques dizaines de km pour les cours d’eau et eaux côtières, de quelques dizaines d’hectares à quelques dizaines de Km² pour les plans d’eau et lagunes, et de plusieurs dizaines de Km² pour les eaux souterraines. Cette unité est désormais couramment utilisée par les acteurs. 
	Les avis demandés doivent reposer sur des appréciations (1) des impacts des activités humaines à l’échelle de la taille des masses d’eau (sans considérer les impacts très localisés)  et (2) des pressions sur lesquelles agir pour restaurer l’état des eaux à ces échelles.
2.	Les impacts qualifient l’incidence des pressions humaines sur chaque masse d’eau. Leur évaluation sert à identifier les pressions qui peuvent empêcher d’atteindre le bon état. L’estimation de ces  impacts a été réalisée avec des données de la surveillance des milieux (qualité et quantité) du bassin, des études locales et de données sur les pressions issues d’outils et méthodes nationaux ou de bassin. Elle possède une validité statistique fondée sur des chroniques de données pluriannuelles et des approches modélisées adaptées à l’échelle et au contexte du bassin. Elle n’a pas pour objet de rendre compte des hétérogénéités locales mais au contraire de faire ressortir les situations contrastées entre les masses d’eau. Leur expertise par les acteurs consultés demande une connaissance de l’étendue des secteurs dégradés ou menacés, des points de pollution ou obstacles majeurs … ainsi que, le cas échéant, une expertise des effets des travaux réalisés, en application des programmes de mesures des SDAGE 2010-2015 et 2016-2021. 
	Il est demandé d’apprécier, à dire d’expert, les niveaux d’impacts proposées (1-faible ;           2-moyen ; 3-fort), en les comparant à la connaissance de la situation des masses d’eau par les acteurs de terrain. Il n’est pas attendu procéder à une vérification des données et des méthodes utilisées pour produire les évaluations proposées.

**Comment by Arkhee** [comment]
ok pour le message en popup c'était une sécurité qui se déclenchait en trop (extension détectée comme vide lorsqu'aucune PJ n'était envoyée), le message est supprimé, effectivement ça n'impactait pas la sauvegarde de l'avis

**Comment by fabiennebarratier** [comment]
ok, le problème est résolu
merci
