### ISSUE TITLE
Petite modification dans le texte : précisions et consignes pour une consultation efficace

### ISSUE THREAD

**Issue by fabiennebarratier** [Arkhee/sdage-consultations2018#8]
une petite coquille s'est glissée dans le dernier paragraphe : "La recevabilité des avis émis dépendra du respect de ces consignes, garantes de la co-construction d'un l'état des lieux 2019 partagé pour élaborer une politique de l'eau dans le bassin, à la fois ambitieuse et réaliste pour la période 2022-2027."

co-construction d'un l'état des lieux 2019 --> merci de corriger : "d'un l'état des lieux 2019" par "d'un état des lieux 2019"

**Comment by Arkhee** [comment]
corrigé
